package com.conveyal.datatools.manager.models;

import com.conveyal.datatools.common.status.MonitorableJob;
import com.conveyal.datatools.manager.persistence.Persistence;
import com.fasterxml.jackson.annotation.JsonProperty;

import java.io.File;
import java.util.Date;

/**
 * A one-time token used to download a feed.
 *
 * Created by demory on 4/14/16.
 */
public class FeedDownloadToken extends Model {

    private static final long serialVersionUID = 1L;

    public String jobId;
    public String filePath;
    public String feedVersionId;
    public String snapshotId;

    public Date timestamp;

    public FeedDownloadToken () { }

    /** Generic download token for file generated by a server job. */
    public FeedDownloadToken (MonitorableJob job) {
        userId = job.retrieveUserId();
        jobId = job.jobId;
        File file = job.retrieveFile();
        filePath = file != null ? file.getAbsolutePath() : null;
        timestamp = new Date();
    }

    public FeedDownloadToken (FeedVersion feedVersion) {
        feedVersionId = feedVersion.id;
        timestamp = new Date();
    }

    public FeedDownloadToken (Snapshot snapshot) {
        snapshotId = snapshot.id;
        timestamp = new Date();
    }

    public FeedDownloadToken (Project project) {
        feedVersionId = project.id;
        timestamp = new Date();
    }

    @JsonProperty("feedVersion")
    public FeedVersion retrieveFeedVersion() {
        if (feedVersionId != null) return Persistence.feedVersions.getById(feedVersionId);
        else return null;
    }

    @JsonProperty("snapshot")
    public Snapshot retrieveSnapshot() {
        if (snapshotId != null) return Persistence.snapshots.getById(snapshotId);
        else return null;
    }

    // TODO: Need to update feedVersionId field name to be more generic (downloadTargetId)
    public Project retrieveProject() {
        return Persistence.projects.getById(feedVersionId);
    }

    public boolean isValid () {
        return true;
    }

}
