version: '3.8'
services:
  download-bundle:
    image: amazon/aws-cli
    command: "s3 cp ${S3_URI} /var/opentripplanner/ --recursive" 
    volumes:
      - type: bind
        source: ./otp
        target: /var/opentripplanner
#      - type: bind
#        source: ~/.aws
#        target: /root/.aws
  # TODO: update status file when OTP is launched
  mark-status-json-as-complete:
    image: docwhat/jq
    command: "jq '.serverStarted = \"true\"' /etc/caddy/static/status.json > /etc/caddy/static/status.json"
    depends_on:
      otp:
        condition: service_healthy
    volumes:
      - type: bind
        source: ./caddy
        target: /etc/caddy/
  otp:
    depends_on:
      download-bundle:
        condition: service_completed_successfully
    image: opentripplanner/opentripplanner:latest
    ports: 
      - "8080:8080"
    command: "--load --serve"
    healthcheck:
      test: [ "CMD", "curl", "localhost/otp" ]
      interval: 10s
      timeout: 3s
      retries: 300
    volumes:
      - type: bind
        source: ./otp
        target: /var/opentripplanner
  caddy:
    image: caddy:latest
    restart: unless-stopped
    volumes:
      - type: bind
        source: ./caddy
        target: /etc/caddy/
    ports:
      - "80:80"
      - "443:443"