version: '3.8'
services:
  download-bundle:
    image: amazon/aws-cli
    command: "s3 cp ${S3_URI} /var/opentripplanner/ --recursive"
    volumes:
      - type: bind
        source: ./otp
        target: /var/opentripplanner
  #      - type: bind
  #        source: ~/.aws
  #        target: /root/.aws
  otp-graph-build:
    depends_on:
      download-bundle:
        condition: service_completed_successfully
    image: amazon/aws-cli
    command: /bin/sh -c "mkdir -p /var/otp/graphs/ && mkdir -p /opt/otp/ && yum install -y openjdk21 nodejs git yarn && yarn global add https://github.com/ibi-group/otp-runner.git && otp-runner /var/opentripplanner/otp-runner-graph-build-manifest.json"
    volumes:
      - type: bind
        source: ./otp
        target: /var/opentripplanner
      - type: bind
        source: ./caddy/static
        target: /usr/share/nginx/client/
  caddy:
    image: caddy:latest
    restart: unless-stopped
    volumes:
      - type: bind
        source: ./caddy
        target: /etc/caddy/
    ports:
      - "80:80"
      - "443:443"